// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZqtjNnom5jcliP4GlY5W6KGaNHDoUNA',
    appId: '1:1000213953817:android:c04a03a2917f5a29b59988',
    messagingSenderId: '1000213953817',
    projectId: 'kigali-directory-2026',
    storageBucket: 'kigali-directory-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhtJ1GA4whjHS-q_1yab9sN2tZRnql24',
    appId: '1:1000213953817:web:7a39b5dace2a7cecb59988',
    messagingSenderId: '1000213953817',
    projectId: 'kigali-directory-2026',
    authDomain: 'kigali-directory-2026.firebaseapp.com',
    storageBucket: 'kigali-directory-2026.firebasestorage.app',
  );
}